HMW/urls.py
from django.urls import path

from . import views

app_name = 'HMW'

urlpatterns = [
    path('HMW/', views.HMWPage, name="HMW"),
    path('root-problem/', views.GeneratePotentialRootProblem.as_view(), name="root-problem"),
    path('generated-5-hmws/<str:value>/', views.GenerateFiveHMW.as_view(), name='five_hmw'),
    path('generate-elevator-pitch/', views.GenerateElevatorPitch.as_view(), name='elevator-pitch'),
    path('update-elevator-pitch/', views.updateElevatorPitch, name='update-elevator-pitch'),
    path('get-problem-statemen-and-whys/', views.getProblemStatementAndWhys, name="get-problem-statement-and-whys")
]

Ranking/urls.py
from django.urls import path

from . import views

app_name = 'Ranking'

urlpatterns = [
    path('ranking/', views.ranking, name="ranking"),
    path('ranking/<int:setting>/', views.ShowLists.as_view(), name="twoLists"),
    path('add-to-table/', views.AddToTable.as_view(), name="add-to-table")
]

Saving/urls.py
from django.urls import path

from . import views

app_name = "Saving"

urlpatterns = [
    path('generate/save/', views.SaveProblemStatement.as_view(), name="saveModel"),
    path('save/<str:operation>/', views.SaveOperation.as_view(), name="saveOperation"),
    path('save/', views.Save.as_view(), name="savePage"),
    path('two_show_popup_venn/<int:instance_id>/', views.TwoPopUpVenn, name='two_show_popup_data'),
    path('three_show_popup_venn/<int:instance_id>/', views.ThreePopUpVenn, name='three_show_popup_data'),
]

Whys/urls.py
from django.urls import path
from . import views

app_name = "Whys"

urlpatterns = [
    path('5-whys/', views.FiveWhys, name="5-whys"),
    path('ranked-problems-statement/<str:pk>/', views.RootProblemStatement.as_view(), name="ranked-problem-statement"),
    path('generate-5-whys/<str:value>/', views.GenerateFiveWhys, name="generate-5-whys"),
    path('two-settings-show-history/<str:pk>/', views.showTwoHistory, name='two-history'),
    path('three-settings-show-history/<str:pk>/', views.showThreeHistory, name='three-history')
]

authenticate/urls.py
from django.urls import path
from . import views

app_name = 'authenticate'

urlpatterns = [
    path('register/', views.SignUpView.as_view(), name='register'),
    path('login/', views.LoginForm.as_view(), name='login'),
    path('signout/', views.signOut, name='signout'),
    path('', views.LoginForm.as_view(), name="login"),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('home/', views.Homepage.as_view(), name="home"),
    path('filter/<str:venn_settings>/', views.VennDiagramFilter.as_view(), name="filter"),
    path('generate/', views.GeneratePS.as_view(), name="generatePS"),
    path('error/', views.errorPage, name="errorPage"),
]

HMW/models.py
from django.db import models

# Create your models here.

HMW/views.py
import re

import openai
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views import View


def HMWPage(request):
    elevator = request.session.get('elevator_pitch')
    context = request.session.get('root_problem')
    return render(request, "hmw.html",
                  {
                      "context": context,
                      "elevator_pitch": elevator
                  })

class GeneratePotentialRootProblem(View):
    def get(self,request):
        pass

    def post(self, request):
        if request.method == "POST":
            listOfWhys = request.POST.getlist("checkbox_group")

            request.session['listOFWhys'] = listOfWhys

            try:
                root_problem = openAiFiveWhys(listOfWhys)
            except Exception as e:
                return redirect('homepage:errorPage')
            request.session['root_problem'] = root_problem
        return redirect("HMW:HMW")


def openAiFiveWhys(listOfWhys):
    openai.api_key = "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"
    reasons_combined = ", ".join(listOfWhys)
    message = (f"Before generating the potential root problem, summarize the whole"
               f"point of the whys, and afterwards, generate a potential root problem based on the following WHY's: {reasons_combined}"
               f"The potential root problem generated should contain the affected people or groups and their impact."
               f"Summarized the generated potential root problem and don't make it too long I suggest"
               f"to have it in 1-sentence format, as it should not be in question form.")

    print(message)
    completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=[{
        "role": "user",
        "content": message
    }])

    print(completion)

    if ":" in completion.choices[0].message.content:
        cut_parts = completion.choices[0].message.content.split(":")
        return cut_parts[1]
    else:
        return completion.choices[0].message.content

class GenerateFiveHMW(View):
    def get(self, request):
        pass

    def post(self, request, value):
        if request.method == "POST":
            try:
                listOfHMWs = openAIFiveHMWs(value)
                elevator_pitch = request.session.get('elevator_pitch')
                if elevator_pitch:
                    del request.session['elevator_pitch']
                data = [
                    {
                        'statement': ps
                    }
                    for ps in listOfHMWs.values()
                ]
                return JsonResponse({"fiveHMWs": data})
            except Exception as e:
                print(e)


        return HttpResponse("ASDAD")

def openAIFiveHMWs(root_problem):

    openai.api_key = "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"

    completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=[{
        "role": "user",
        "content": (f"Given the potential root problem which is {root_problem}, understand the idea of the given "
                    f"root potential problem, and generate 5-How Might We statement. Take note that you should only "
                    f"generate 5 How Might We and nothing else.")
    }])

    response_list = completion.choices[0].message.content.split('\n')

    questions_dict = {}

    for i, question in enumerate(response_list, start=1):
        # Split each question and take the second part (after the dot)
        question_without_number = question.split('. ', 1)[1].strip()
        questions_dict[i] = question_without_number

    return questions_dict


class GenerateElevatorPitch(View):
    def get(self, request):
        pass

    def post(self, request):
        if request.method == "POST":
            HMW = request.POST.getlist('checkbox_group')
            root_problem = request.session.get('root_problem')
            elevator = openAIElevatorPitch(HMW, root_problem)

            print("\n\n")
            print(elevator)
            print("\n\n\n")
            capitalized_words_to_avoid = ['FOR', 'WHO', 'WE PROVIDE', 'THAT', 'UNLIKE', 'OUR SOLUTION', 'THAT']

            pattern = '|'.join(r'\b{}\b'.format(re.escape(word)) for word in capitalized_words_to_avoid)

            # Split the elevator string using the pattern
            result = re.split(pattern, elevator)

            # Filter out empty strings from the result
            result = [phrase.strip() for phrase in result if phrase.strip()]

            request.session['elevator_pitch'] = result

            print(len(result))

            for i in result:
                print(i)

        return redirect('HMW:HMW')



def openAIElevatorPitch(HMW, root_problem):
    openai.api_key = "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"

    hmw_combined = ", ".join(HMW)

    completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=[{
        "role": "user",
        "content": f"Generate only 1 elevator pitch based on this given How might we statements: {hmw_combined}."
                   "Please answer each of the following capitalized word only. In generating your response,"
                   "the capitalized word should always be in it. There are 8 capitalized words needed to be answered."
                   "FOR [the target consumer], WHO [specific needs, requirements, demands, criteria],"
                   "WE PROVIDE [solution or description], THAT [gives specific benefits/value to clients],"
                   " UNLIKE [the competition], WHO [provide a solution, features, functions, benefits], "
                   "OUR SOLUTION [better approach, solution, functions, benefits, technology], THAT [offers a "
                   "better customer experience]."
    }])


    return completion.choices[0].message.content


def updateElevatorPitch(request):

    elevator_content = request.POST.getlist('elevator_content')

    request.session['elevator_pitch'] = elevator_content

    return redirect('HMW:HMW')


def getProblemStatementAndWhys(request):
    fiveWhys = request.session.get('listOFWhys')

    print(fiveWhys)

    selectedPS = request.session.get('ranked_problem')

    return JsonResponse({
        'ranked_ps': selectedPS,
        'fiveWhys': fiveWhys
    })

Ranking/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View

from Saving.models import TwoProblemStatement, ThreeProblemStatement


# This method is only use for redirecting to that page
def ranking(request):
    context = request.session.get('selected_checkboxes_table')

    store = request.session.get('ranked_problem')

    print(store)

    return render(request, "Ranking.html", {
        "context": context,
        "ranking_setting": request.session.get('ranking_setting'),
        "valid": request.session.get('valid'),
        "root_problem": request.session.get('ranked_problem')
    })


class ShowLists(View):
    @method_decorator(login_required(login_url="authenticate:login"))
    def get(self, request, setting):
        pass

    def post(self, request, setting):
        global data
        if request.method == "POST":
            request.session['ranking_setting'] = setting

            if setting == 2:
                auth = request.session.get('auth')
                user = User.objects.get(username=auth["username"])

                twoPS = TwoProblemStatement.objects.filter(user_fk=user)

                data = [
                    {
                        'id': ps.id,
                        'statement': ps.statement,
                        'user_fk': ps.user_fk.id,
                        'venn_fk': ps.venn_fk.id if ps.venn_fk else None,
                    }
                    for ps in twoPS
                ]
                data = {'data': data}
                return JsonResponse(data)
            elif setting == 3:
                auth = request.session.get('auth')
                user = User.objects.get(username=auth["username"])

                threePS = ThreeProblemStatement.objects.filter(user_fk=user)
                data = [
                    {
                        'id': ps.id,
                        'statement': ps.statement,
                        'user_fk': ps.user_fk.id,
                        'venn_fk': ps.venn_fk.id if ps.venn_fk else None,
                    }
                    for ps in threePS
                ]

                data = {'data': data}
                return JsonResponse(data)

        return HttpResponse("FAILED")


class AddToTable(View):
    def get(self, request):
        pass;

    def post(self, request):
        if request.method == "POST":
            selected_checkboxes = request.POST.getlist('checkbox_group')

            auth = request.session.get('auth')
            user = User.objects.get(username=auth["username"])

            PS_list = []

            setting = request.session.get('ranking_setting')

            if setting == 2:
                for checkbox_value in selected_checkboxes:
                    twoPS_instance = TwoProblemStatement.objects.filter(user_fk=user, statement=checkbox_value)
                    PS_list.append(twoPS_instance)
            else:
                for checkbox_value in selected_checkboxes:
                    three_PS = ThreeProblemStatement.objects.filter(user_fk=user, statement=checkbox_value)
                    PS_list.append(three_PS)

            new_context = {
                'items': [
                    {'id': item.id, 'statement': item.statement}
                    for queryset in PS_list
                    for item in queryset
                ]
            }

            request.session['selected_checkboxes_table'] = new_context
            request.session['valid'] = True if len(selected_checkboxes) > 2 else False

            return redirect('Ranking:ranking')
        return HttpResponse("No")

Whys/views.py
import openai
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views import View

from Saving.models import TwoProblemStatement, ThreeProblemStatement


# Create your views here.
def FiveWhys(request):
    root_problem = request.session.get('ranked_problem')
    pk = request.session.get('pk_rankedPS')
    setting = request.session.get('ranking_setting')

    return render(request, "Whys.html",
                  {
                      "rankedPS": root_problem,
                      "pk": pk,
                      "setting": setting
                  })


class RootProblemStatement(View):
    def get(self, request):
        pass

    def post(self,request, pk):
        if request.method == "POST":

            request.session['pk_rankedPS'] = pk

            root_problem = request.POST.get('radiobutton_group')

            rp = request.session.get('root_problem')
            if rp:
                del request.session['root_problem']
            fw = request.session.get('fiveWhys')
            if fw:
                del request.session['fiveWhys']
            ranked_prob = request.session.get('ranked_problem')

            if ranked_prob:
                del request.session['ranked_problem']

            request.session['ranked_problem'] = root_problem

            return redirect('Whys:5-whys')



def GenerateFiveWhys(request, value):
    if request.method == "POST":
        generated_five_whys = openAiFiveWhy(value)

        data = [
            {
                'statement': ps
            }
            for ps in generated_five_whys.values()
        ]

        request.session['fiveWhys'] = data

        print(data)

        return JsonResponse({
            "fiveWhys": data
        })


    return HttpResponse("POST")

def openAiFiveWhy(value):
    openai.api_key = "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"

    completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=[{
        "role": "user",
        "content": f"Subject the {value} to a 5-Why analysis. "
                   f"Generate five whys to uncover the underlying issue behind {value}. Make it relevant to the {value} and understandable."
                   f"Please dont include any explanation just generate all the whys statement."

    }])

    response_list = completion.choices[0].message.content.split('\n')

    print(response_list)

    questions_dict = {}

    for i, question in enumerate(response_list, start=1):
        # Split each question and take the second part (after the dot)
        question_without_number = question.split('. ', 1)[1].strip()
        questions_dict[i] = question_without_number

    return questions_dict


def showTwoHistory(request, pk):
    ranking_setting = request.session.get('ranking_setting')
    new_pk = int(pk)
    twoPS = TwoProblemStatement.objects.get(id=pk)
    venn = twoPS.venn_fk
    data = {
        'field1': venn.field1,
        'field2': venn.field2,
        'filter': venn.filter
    }

    print(type(new_pk))

    return JsonResponse(
        {
            'data': data,
            'setting': ranking_setting
        }
    )


def showThreeHistory(request, pk):
    ranking_setting = request.session.get('ranking_setting')
    new_pk = int(pk)
    threePS = ThreeProblemStatement.objects.get(id=pk)
    venn = threePS.venn_fk

    data = {
        'field1': venn.field1,
        'field2': venn.field2,
        'field3': venn.field3,
        'filter': venn.filter

    }

    return JsonResponse(
        {
            'data': data,
            'setting': ranking_setting
        }
    )

templates/error.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="/static/css/error.css" />
        <title>Document</title>
        <script>
            document.addEventListener("DOMContentLoaded", function() {
                var homepageButton = document.getElementById("homepage")

                homepageButton.addEventListener("click", function() {
                    window.location.href = {% url 'homepage:home' %}
                })
            })
        </script>
    </head>
    <body>
        <div class="container">
            <div class="content-container">
                <h1>Oops! Something went wrong.</h1>
                <p>
                    It appears somethent went wrong. Please proceed to our
                    homepage.
                </p>
                <img src="/static/media/error.svg" />
                <button class="homepage-button" id="homepage" >Go home</button>
            </div>
        </div>
    </body>
</html>

templates/save.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/css2?family=Lexend+Deca&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="/static/css/save.css" />
    <title>ElevateMe</title>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="{% static 'script/save.js' %}"></script>
    <script>
        function updateAction(form) {
            var radioButtons = form.querySelectorAll('input[name="radiobutton_group"]:checked');

            if (radioButtons.length > 0) {
                var checkedRadioButton = radioButtons[0];
                var operation = checkedRadioButton.id;

                form.action = '/save/' + operation + '/';
            } else {
                form.method = "get"
                form.action = '{% url 'Saving:savePage' %}'
                alert('Please select a radio button before submitting.');
            }
        }


        function updateCheckboxValue(form) {
            var cards = form.querySelectorAll('.card');
            cards.forEach(function (card) {
                var statement = card.querySelector('.card-text').innerText.trim();
                var checkbox = card.querySelector('.checkbox');
                if (checkbox) {
                    checkbox.value = statement;
                }
            });
        }

        function showPopupVenn2(button) {
            var popup = document.getElementById('showHistoryPopupVenn2');

            if (popup) {
                popup.style.display = 'block';

                var buttonValue = button.value;

                $.ajax({
                    url: `/two_show_popup_venn/${buttonValue}/`,
                    type: 'POST',  // Change to POST method
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}',  // Include the CSRF token
                    },
                    dataType: 'json',
                    success: function (data) {


                        document.getElementById('venn1').textContent = data.field1;
                        document.getElementById('venn2').textContent = data.field2;

                        document.getElementById('field1').value = data.field1;
                        document.getElementById('field2').value = data.field2;
                        document.getElementById('filterVenn2').value = data.filter;

                        // Update your popup or do whatever you need with the data
                    },
                    error: function (error) {
                        console.error('Error fetching data:', error);
                    }
                });
            } else {
                console.error('Popup element not found');
            }
        }


        function showPopupVenn3(button) {
            var popup = document.getElementById('showHistoryPopupVenn3');

            if (popup) {
                popup.style.display = 'block';

                var buttonValue = button.value;

                $.ajax({
                    url: `/three_show_popup_venn/${buttonValue}/`,
                    type: 'POST',
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}',  // Include the CSRF token
                    },
                    dataType: 'json',
                    success: function (data) {

                        console.log(data);

                        document.getElementById('venn3.1').textContent = data.field1;
                        document.getElementById('venn3.2').textContent = data.field2;
                        document.getElementById('venn3.3').textContent = data.field3;

                        document.getElementById('fieldVenn3.1').value = data.field1;
                        document.getElementById('fieldVenn3.2').value = data.field2;
                        document.getElementById('fieldVenn3.3').value = data.field3;
                        document.getElementById('filterVenn3').value = data.filter;

                    },
                    error: function (error) {
                        console.error('Error fetching data:', error);
                    }
                });
            } else {
                console.error('Popup element not found');
            }
        }

    </script>
</head>

<body>
    <div class="container">
        <div class="elevateme">ElevateMe</div>
        <div class="buttons">
            <a href="{% url 'homepage:home' %}"><input class="button1" type="button" value="Home" /></a>
            <a href="{% url 'Saving:savePage' %}"><input class="button-clicked" type="button" value="Saved" /></a>
            <a href="{% url 'Ranking:ranking' %}"><input class="button1" type="button" value="Ranking" /></a>
            <a href="{% url 'Whys:5-whys' %}"><input class="button1" type="button" value="5-Whys" /></a>
            <a href="{% url 'HMW:HMW' %}"><input class="button1" type="button" value="5-HMW" /></a>
            <a href="{% url 'authenticate:signout' %}"><input class="button1" type="button" value="Sign Out" /></a>
        </div>
    </div>
    <div class="savedlist">
        <h1>Saved List</h1>
        <div class="vennDiagram2">
            <h2>2 Venn Diagram List</h2>
            <div class="outside-container">
                <div class="vennDiagram2-container">
                    <div class="cards-container" id="vennDiagram2Container">
                        <form action="{% url 'Saving:saveOperation' '0' %}" id="saveForm1" method="post">
                            {% csrf_token %}
                            {% for instance in twoPS_data %}
                            <div class="card" id="{{ instance.id }}">
                                <input type="radio" class="checkbox" name="radiobutton_group" id="{{ instance.id }}"
                                    value="{{ instance.statement }}" />
                                <div class="card-text" contenteditable="true">
                                    {{ instance.statement }}
                                </div>
                                <!-- pop up show History button -->
                                <button class="buttonTheme1" type="button" name="show-button" value="{{ instance.id }}" id="showButton1"
                                    onclick="showPopupVenn2(this)">
                                    show
                                </button>
                            </div>
                            {% endfor %}
                            <button class="edit-button" type="submit" name="button" value="button2.1" id="update2"
                                onclick="updateAction(this.form); updateCheckboxValue(this.form)">
                                Update
                            </button>
                            <button class="delete-button" type="submit" name="button" value="button2.2" id="delete2"
                                onclick="updateAction(this.form)">
                                Delete
                            </button>
                        </form>
                        <div id="showHistoryPopupVenn2" class="popup">
                            <!-- Venn Diagram 2 circle drawing -->
                            <div class="venn-diagram-container">
                                <div class="venn-circle1">
                                    <span class="circle-label1" id="venn1">Label 1</span>
                                </div>

                                <div class="venn-circle2">
                                    <span class="circle-label2" id="venn2">Label 2</span>
                                </div>
                            </div>
                            <!-- Venn Diagram Settings -->
                            <div class="vennSettings">
                                <h2>Venn Diagram Settings</h2>
                                <form id="popupForm1" action="{% url 'homepage:filter' '2' %}" method="post">
                                    {% csrf_token %}
                                    <label for="field1">Field 1:</label>
                                    <textarea id="field1" name="field1" placeholder="Input scope here..."></textarea><br>

                                    <label for="field2">Field 2</label>
                                    <textarea id="field2" name="field2" placeholder="Input scope here..."></textarea><br>

                                    <label for="filter"> Filter: </label>
                                    <textarea id="filterVenn2" name="filter" rows="5"></textarea><br>

                                    <button class="buttonTheme1" type="submit" id="inputVenn2">Input</button>
                                    <button class="button-input" type="button" id="close"
                                            onclick="closePopup()">Close</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="vennDiagram3">
            <h2>3 Venn Diagram List</h2>
            <div class="vennDiagram3-container">
                <div class="cards-container" id="vennDiagram3Container">
                    <form action="{% url 'Saving:saveOperation' 0 %}" id="saveForm2" method="post">
                        {% csrf_token %}
                        {% for instance in threePS_data %}
                        <div class="card" id="{{ instance.id }}">
                            <input type="radio" class="checkbox" name="radiobutton_group" id="{{ instance.id }}"
                                value="{{ instance.statement }}" />
                            <div class="card-text" contenteditable="true">
                                {{ instance.statement }}
                            </div>
                              <!-- pop up show History button -->
                              <button class="buttonTheme1" type="button" name="button" value="{{ instance.id }}" id="showButton2"
                              onclick="showPopupVenn3(this)">
                              show
                          </button>
                        </div>
                        {% endfor %}
                        <button type="submit" class="edit-button" name="button" value="button3.1" id="update2"
                            onclick="updateAction(this.form); updateCheckboxValue(this.form)">
                            Update
                        </button>
                        <button class="delete-button" type="submit" name="button" value="button3.2" id="delete2"
                            onclick="updateAction(this.form)">
                            Delete
                        </button>
                    </form>
                    <div id="showHistoryPopupVenn3" class="popup">
                        <!-- Venn Diagram 3 circle drawing -->
                        <div class="venn-diagram-container" id="venn-diagram-container3">
                            <div class="venn-circle1">
                                <span class="circle-label1" id="venn3.1">Label 1</span>
                            </div>

                            <div class="venn-circle2">
                                <span class="circle-label2" id="venn3.2">Label 2</span>
                            </div>
                            <div class="venn-circle3">
                                <span class="circle-label3" id="venn3.3">Label 3</span>
                            </div>
                        </div>
                        <!-- Venn Diagram Settings -->
                        <div class="vennSettings">
                            <h2>Venn Diagram Settings</h2>
                            <form id="popupForm2" action="{% url 'homepage:filter' '3' %}" method="post">
                                {% csrf_token %}
                                <label for="field1">Field 1:</label>
                                <textarea id="fieldVenn3.1" name="field1" placeholder="Input scope here..."></textarea><br>

                                <label for="field2">Field 2</label>
                                <textarea id="fieldVenn3.2" name="field2" placeholder="Input scope here..."></textarea><br>

                                <label for="field3">Field 3</label>
                                <textarea id="fieldVenn3.3" name="field3" placeholder="Input scope here..."></textarea><br>


                                <label for="filter"> Filter: </label>
                                <textarea id="filterVenn3" name="filter" rows="3"></textarea><br>

                                <button class="buttonTheme1" type="submit" id="inputVenn3">Input</button>
                                <button class="button-input" type="button" id="close"
                                        onclick="closePopup()">Close</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'script/save.js' %}"></script>
</body>

</html>